services:
    app:
        image: younesbousfiha/synenergy-api
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            -   .:/var/www
        networks:
            - mynetwork
        depends_on:
            - mysql
        ports:
            - "8000:80"
        environment:
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    mysql:
        image: mysql:latest
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - mynetwork
        ports:
            - "3307:3306"

    # Networks
networks:
    mynetwork:
        driver: bridge

# Volumes
volumes:
    mysql-data:
        driver: local
